### ISSUE TITLE
Errors in build phase

### ISSUE THREAD

**Issue by yuchi** [askovpen/node-fidonet-mailer-binkp-crypt#10]
Looks like I’m getting a lot of errors on Travis CI because of this package.

Could you please have a look at this [errored build log](https://travis-ci.org/smclab/titaniumifier/jobs/73849489)?

Could also be just an issue with Travis, since it worked before…

**Comment by askovpen** [comment]
try 0.0.34

**Comment by askovpen** [comment]
or update adm-zip to 0.4.7

**Comment by yuchi** [comment]
The fact is that I had serious issues with `adm-zip@0.4.7` (see smclab/titaniumifier#32).

Gonna tackle it somehow. Let’s see if I can force a newer version of _fidonet-mailer-binkp-crypt_ without updating _adm-zip_.

**Comment by askovpen** [comment]
adm-zip@0.4.5? :-)

**Comment by yuchi** [comment]
What do you mean? (I probably didn’t get the joke :sob:)

**Comment by askovpen** [comment]
reinstall adm-zip@0.4.6. in depends  fidonet-mailer-binkp-crypt>0.0.20
it install 0.0.34

**Comment by yuchi** [comment]
Oh, you updated `fidonet-mailer-binkp-crypt`! Gonna relaunch the build now.

**Comment by yuchi** [comment]
:tada: Awesome! Now my tests fail for completely different reasons, but it’s ok! :P

**Comment by yuchi** [comment]
Thank you for the fast response!

(btw now my tests pass)

**Comment by askovpen** [comment]
yw. adm-zip have only on version 0.4.5(0.4.6) depend fidonet-mailer-binkp-crypt. other versions without this depend.

**Comment by yuchi** [comment]
Still cannot pass to `0.4.7` for other issues (empty files after unzipping).
