### ISSUE TITLE
Use nan

### ISSUE THREAD

**Issue by 19h** [askovpen/node-fidonet-mailer-binkp-crypt#4]
Yo,

we're currently deploying decompress and it is cross-dependent on this module; as you're currently pushing 0.12 support, I'd love to see it using [nan](https://github.com/rvagg/nan), as that will provide you with both 0.12 and io.js (1.1.0) support.

Frankly, nan will provide an future-proof ABI that will be compatible to future versions of both node and io.js by simply bumping the nan version in the package.json!

Thanks.

**Comment by askovpen** [comment]
yes. nan

**Comment by 19h** [comment]
Is that an indicator that you're working on this issue or was this a "no"?

**Comment by jorrit** [comment]
Thanks for implementing nan this quickly!

**Comment by askovpen** [comment]
@KenanSulayman nan implemented before your issue :-)

**Comment by 19h** [comment]
What! The! You're quick. Awesome! Thanks :+1:
